AddonCategory = AddonCategory or {}
local AddonCategory = AddonCategory

AddonCategory.defaultSV = {
    listCategory = {
        "User Interface", 
        "Trackers", 
        "Combat",
        "PvE", 
        "PvP", 
        "Util", 
        "Map", 
        "Class"
    },
    sectionsOpen = {},
    ["AlignGrid"] = "User Interface",
    ["Azurah"] = "User Interface",
    ["CombatMetronome"] = "User Interface",
    ["CombatReticle"] = "User Interface",
    ["FancyActionBar+"] = "User Interface",
    ["LuiExtended"] = "User Interface",
    ["IIfA"] = "User Interface",
    ["PerfectPixel"] = "User Interface",

    ["Acuity"] = "Trackers",
    ["Cooldowns"] = "Trackers",
    ["DebuffMe"] = "Trackers",
    ["HyperTools"] = "Trackers",
    ["MayIBash"] = "Trackers",
    ["MKTracker"] = "Trackers",
    ["RoaringOpportunist"] = "Trackers",
    ["Siroria"] = "Trackers",
    ["Srendarr"] = "Trackers",
    ["Synergy"] = "Trackers",

    ["CombatMetrics"] = "Combat",
    ["PerfectWeave"] = "Combat",
    ["SynergyToggle"] = "Combat",
    ["WizardsWardrobe"] = "Combat",

    ["AsylumNotifier"] = "PvE",
    ["AsylumOlorime"] = "PvE",
    ["AsylumTracker"] = "PvE",
    ["BearNecessities"] = "PvE",
    ["BRHelper"] = "PvE",
    ["CombatAlerts"] = "PvE",
    ["CRHelper"] = "PvE",
    ["CrutchAlerts"] = "PvE",
    ["HodorReflexes"] = "PvE",
    ["HowToCloudrest"] = "PvE",
    ["HowToKyne"] = "PvE",
    ["HowToKynesAegis"] = "PvE",
    ["HowToSunspire"] = "PvE",
    ["OdySupportIcons"] = "PvE",
    ["PlayerRoleIcon"] = "PvE",
    ["QcellDreadsailReefHelper"] = "PvE",
    ["QcellRockgroveHelper"] = "PvE",
    ["RaidNotifier"] = "PvE",
    ["Speedrun"] = "PvE",
    ["TWPHoF"] = "PvE",
    ["TWPKA"] = "PvE",

    ["AutoReleaseInBG"] = "PvP",
    ["BetterScoreboard"] = "PvP",
    ["RdKGroupTool"] = "PvP",

    ["AddonCategory"] = "Util",
    ["AutoCategory"] = "Util",
    ["BugCatcher"] = "Util",
    ["Constellations"] = "Util",
    ["DolgubonsLazyWritCreator"] = "Util",
    ["GroupManager"] = "Util",
    ["HowLong"] = "Util",
    ["PithkaAchievementTracker"] = "Util",
    ["PotionMaker"] = "Util",
    ["Recharge"] = "Util",
    ["SuperStar"] = "Util",
    ["TamrielTradeCentre"] = "Util",
    ["TextureIt"] = "Util",
    ["USPF"] = "Util",

    ["BeamMeUp"] = "Map",
    ["CircularMinimap"] = "Map",
    ["HarvestMap"] = "Map",
    ["HarvestMapAD"] = "Map",
    ["HarvestMapDC"] = "Map",
    ["HarvestMapDLC"] = "Map",
    ["HarvestMapEP"] = "Map",
    ["HarvestMapNF"] = "Map",
    ["LoreBooks"] = "Map",
    ["LostTreasure"] = "Map",
    ["MapPins"] = "Map",
    ["VotansMiniMap"] = "Map",

    ["BoundArmamentsCounter"] = "Class",
    ["CrystalFragmentsProc"] = "Class",
    ["GrimFocusCounter"] = "Class",
    ["HowToBeam"] = "Class",
    ["ShowBlast"] = "Class",
}